name: Canary

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  Canary:
    if: (github.repository == 'aws-deadline/${{inputs.repository}}')
    name: Canary
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        if: ${{inputs.branch == 'mainline' || inputs.branch == 'release'}}
        with:
          ref: ${{inputs.branch}}
          
      - name: Configure AWS credentials for release
        if: ${{inputs.branch == 'release'}}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_CANARY_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
       
      - name: Configure AWS credentials for mainline
        if: ${{inputs.branch == 'mainline'}}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_CANARY_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
        
      - name: Run Canary for Mainline
        timeout-minutes: 120
        if: ${{inputs.branch == 'mainline'}}
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{inputs.repository}}-${{inputs.branch}}-${{inputs.os}}-canary
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
              TEST_TYPE,
              OPERATING_SYSTEM
        env:
          TEST_TYPE: WHEEL
          OPERATING_SYSTEM: ${{inputs.os}}

      - name: Run Canary for Release
        timeout-minutes: 120
        if: ${{inputs.branch == 'release'}}
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{inputs.repository}}-${{inputs.branch}}-${{inputs.os}}-canary
          source-version-override: refs/heads/release
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
              OPERATING_SYSTEM
        env:
          OPERATING_SYSTEM: ${{inputs.os}}